trigger:
  - main

pool:
  name: Default

variables:
  POSTGRES_DB: mrp_db
  POSTGRES_USER: mrp_user
  DB_URL: jdbc:postgresql://localhost:5432/mrp_db
  DB_USERNAME: mrp_user

steps:
  - script: |
      docker compose up -d
      sleep 20
      docker ps
    displayName: 'Start PostgreSQL Database for Tests'
    env:
      POSTGRES_DB: $(POSTGRES_DB)
      POSTGRES_USER: $(POSTGRES_USER)
      POSTGRES_PASSWORD: $(DB_PASSWORD)

  - task: Maven@3
    displayName: 'Build and Test with Maven'
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.21'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'clean package'
    env:
      DB_URL: $(DB_URL)
      DB_USERNAME: $(DB_USERNAME)
      DB_PASSWORD: $(DB_PASSWORD)

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Executable JAR Artifact'
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/target/Media-Ratings-Platform-1.0-SNAPSHOT.jar'
      artifact: 'media-ratings-platform-jar'
      publishLocation: 'pipeline'